### PR TITLE
update to 2.0.0 which is python 3.6 only

### PR DESCRIPTION
**Pull request by kain88-de**
@ocefpaf is this OK to build on python >3.6 only?

### CODE REVIEW

**Comment by ocefpaf** [comment]
If it does not work with  <36 sure. You will need to rerender though.

**Comment by kain88-de** [comment]
I've done the rerender. Thanks for the clarification.

**Comment by kain88-de** [comment]
@ocefpaf I think I accidentally messed this up. The version of xdg in conda-forge is now `2.0.0-0`, while I would have expected it to be `2.0.0-py36_0`. I'm not sure if this is an issue when py3.7 comes out.

**Comment by isuruf** [comment]
Yes, you should add `skip: True  # [py<36]` instead of adding the constraint on python version

**Comment by ocefpaf** [comment]
There is nothing wrong with the package though. `conda` won't install it in any other Python, only 3.6, and it will automatically choose 3.6 if nothing else is selected. The constraints are "correct" and you don't need to make conda believe that this has a Python matrix and then skip the rest only to get a `py36` build string.

The build string is for humans, `conda` does not do anything with that.

**Comment by isuruf** [comment]
@ocefpaf, no it's wrong. You can install it in python > 3.6 since the run requirement is `python >=3.6`

**Comment by kain88-de** [comment]
I tested with python 2.7 and conda will choose the old version not 2.0.0. So the constraints work. I can test with py3.5 later today.

**Comment by ocefpaf** [comment]
> @ocefpaf, no it's wrong. You can install it in python > 3.6 since the run requirement is `python >=3.6`

Indeed but I thought that was by design, right @kain88-de?

**Comment by kain88-de** [comment]
well I like that. This means the package is automatically installable on py3.7 without further changes. I just wanted to make sure this is as intended and is the same solution other packages on conda-forge use.

**Comment by isuruf** [comment]
You will be able to install in Python 3.7, but it will not work unless you make this package noarch

**Comment by kain88-de** [comment]
why won't it work?

**Comment by isuruf** [comment]
Because the package is installed into `lib/python3.6/site-packages`. This can be fixed when you make the package `noarch: python`

**Comment by ocefpaf** [comment]
> Because the package is installed into `lib/python3.6/site-packages`.

Yep. That is a `conda` limitation that we forget when we get too comfortable with `pip` :wink:

**Comment by kain88-de** [comment]
But the package skips the windows platform. Does this still work with *noarch* then? I remember there was some discussion about this on other packages.

**Comment by isuruf** [comment]
It won't. So, the only option is to go back to the original way and add `skip: True  # [py <36]` and rerender when py3.7 comes along

**Comment by ocefpaf** [comment]
> It won't. So, the only option is to go back to the original way and add `skip: True  # [py <36]` and rerender when py3.7 comes along

Unfortunately that is true. It is sad though that the `noarch` is limited that way.

**Comment by kain88-de** [comment]
I'll prepare an update to the package tomorrow.

**Pull request merged**
