### PR TITLE
added aarch64 support

### PR DESCRIPTION
**Pull request by nerohmot**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nerohmot** [comment]
@conda-forge-admin, please rerender

**Comment by kain88-de** [comment]
This is a noarch package? Why does this need  explicit support?

**Comment by nerohmot** [comment]
sorry to say, but this package is a none-noarch package (as the linter was correctly complaining about), please have a look, it is linux-64 and osx64 only ... cfr : https://anaconda.org/conda-forge/xdg

**Comment by nerohmot** [comment]
Ok, looked at the source, and noarch is the best way to go as xdg uses pathlib from the standard library, which one in turn is windows and posix complient :1st_place_medal: 
Things can't stay as they are now, as both win and aarch are excluded :-(
Shall I do or do you do ?

**Comment by kain88-de** [comment]
@conda-forge-admin, please add noarch: python

**Review by kain88-de — APPROVED** [review]

**Comment by kain88-de** [comment]
@conda-forge-admin, please rerender

**Comment by kain88-de** [comment]
@nerohmot thanks for the push to update the package.

**Pull request merged**
